// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCWjVNYUk_6V_t3zWRgunUnL6zZ12_c4no',
    appId: '1:453840859755:web:e8c0c9d8cb36326bdbb72e',
    messagingSenderId: '453840859755',
    projectId: 'registration-b9a9f',
    authDomain: 'registration-b9a9f.firebaseapp.com',
    storageBucket: 'registration-b9a9f.firebasestorage.app',
    measurementId: 'G-MPGDXMLXDR',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyA5V2Pl1ITXpR-FP2ki98kjdBQ_8a1fuGs',
    appId: '1:453840859755:android:4408f540b664cd3cdbb72e',
    messagingSenderId: '453840859755',
    projectId: 'registration-b9a9f',
    storageBucket: 'registration-b9a9f.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyB-xMxCk6uNG08HDMjN4aHU6qmDsa9zZ_k',
    appId: '1:453840859755:ios:03588f2d7a237548dbb72e',
    messagingSenderId: '453840859755',
    projectId: 'registration-b9a9f',
    storageBucket: 'registration-b9a9f.firebasestorage.app',
    iosBundleId: 'com.example.loginApp',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyB-xMxCk6uNG08HDMjN4aHU6qmDsa9zZ_k',
    appId: '1:453840859755:ios:03588f2d7a237548dbb72e',
    messagingSenderId: '453840859755',
    projectId: 'registration-b9a9f',
    storageBucket: 'registration-b9a9f.firebasestorage.app',
    iosBundleId: 'com.example.loginApp',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyCWjVNYUk_6V_t3zWRgunUnL6zZ12_c4no',
    appId: '1:453840859755:web:a76532e442feb13edbb72e',
    messagingSenderId: '453840859755',
    projectId: 'registration-b9a9f',
    authDomain: 'registration-b9a9f.firebaseapp.com',
    storageBucket: 'registration-b9a9f.firebasestorage.app',
    measurementId: 'G-YYG07GT9RG',
  );
}
